### PR TITLE
Smarter option to allow more players the ability to heal

### PR DESCRIPTION
**Pull request by tylers-dev**
Leave all the same types of units (Medic, Sniper, Diver, Engineer). However, convert snipers and divers into medics but give them the loadout of a sniper or diver. This way Medics, Snipers, Divers can use medkits to heal themselves.

### CODE REVIEW

**Comment by Gigatek1** [comment]
This could work. I do play as engineer when I play. You get a mine detector that works and a toolkit to pick locks plus you can use the spawn detector. I think we should keep the engineers as is but replace the diver and sniper with medics. Just need to make sure they have no added bonuses like the sniper can hold his breath to shoot longer and the diver can see further in water (I have no idea about this but I dont think this is the case). Also I think the scripts that load players out, work on class not position of the spawn so we would have to work that out.

**Comment by Gigatek1** [comment]
Oh I see what you did. Sorry I was thinking this was your first pull request. I need to test this

**Comment by Gigatek1** [comment]
Use this repo. This is the old one.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis

**Comment by tylers-dev** [comment]
Done. Moved to the right repo.
https://github.com/A3Armory/A3A_A3Wasteland_Sock.Altis/pull/1

I totally agree. I had forgot the class advantage an engineer has, is the
toolkit to repair a vehicle. I know most people have repair kits, but an
engineer essentially can repair as many times as they want with a toolkit.

I did research to see if the sniper or diver class has any unique arma
ability, I haven't discovered any. Thats why it was simple enough to make
them medics but still give them the gear that make them different.

**Pull request closed without merging**
